# Jekyll Resume Theme

# Site settings
title: Carolina Carriazo
email: carolcarriazo@gmail.com
description: Tech writer, marketing manager, and occasional coder.
baseurl: ""
url: ""
location: London, UK
github_username:  carolcarriazo
codepen_username:  carolcarriazo
email_address: carolcarriazo@@gmail.com

# Build settings
markdown: kramdown

collections:
  poems:
    output: true