# Jekyll Resume Theme

# Site settings
title: Carolina Carriazo
email: carolcarriazo@gmail.com
description: Tech writer, developer, and occasional poet.
baseurl: ""
url: ""
location: Chicago, IL
github_username:  carolcarriazo
codepen_username:  carolcarriazo
email_address: carolcarriazo@@gmail.com

# Build settings
markdown: kramdown
