title: carol's blog
baseurl: ""
description: carving out my little corner of internet.
url: carolcarriazo.github.io
date_format: "%d-%m-%Y"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics:
email: carolcarriazo@gmail.com