openapi: 3.0.1
info:
  title: Sample Pets API
  description: A placeholder API spec to demonstrate Swagger UI embedding.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
paths:
  /pets:
    get:
      summary: List all pets
      description: Retrieve a list of pets.
      responses:
        '200':
          description: A JSON array of pet objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      description: Retrieve a single pet by its ID.
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: A pet object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 123
        name:
          type: string
          example: "Fluffy"
        tag:
          type: string
          example: "cat"
